name: Build Docker Image
on:
    push:
        branches: ["dev-scaleway"]
    #pull_request:
    #  branches: ["main", "dev"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Login to Scaleway Container Registry
            uses: docker/login-action@v3
            with:
                username: nologin
                password: ${{ secrets.SCALEWAY_API_KEY }}
                registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
        -   name: Build the Docker image
            run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
        -   name: Push the Docker Image
            run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
        
    deploy:
        # Deployment job
        runs-on: ubuntu-latest
        needs: build

        steps:
        #-   name: Install SSH Key
        #    uses: webfactory/ssh-agent@v0.7.0
        #    with:
        #        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        -   name: Login to Scaleway Container Registry
            uses: docker/login-action@v3
            with:
                username: nologin
                password: ${{ secrets.SCALEWAY_API_KEY }}
                registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
        -   name: Deploy to VM via SSH
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                    
                    docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
                    docker stop ml-app-deploy || true
                    docker rm ml-app-deploy || true
                    docker run -d --name ml-app-deploy -p 8000:8000 ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
