name: Build Docker Image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag haroldhang/atut-devops-team4:v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        ecr: auto
        logout: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Extract metadata (labels, tags, etc.) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: haroldhang/atut-devops-team4:v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: haroldhang/atut-devops-team4:v2
          labels: ${{ steps.meta.outputs.labels }}
  