name: Build Docker Image
on:
    push:
        branches: ["dev-scaleway"]
    #pull_request:
    #  branches: ["main", "dev"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Login to Scaleway Container Registry
            uses: docker/login-action@v3
            with:
                username: nologin
                password: ${{ secrets.SCALEWAY_API_KEY }}
                registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
        -   name: Build the Docker image
            run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
        -   name: Push the Docker Image
            run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
        
