name: Build Docker Compose Images
on:
    push:
        branches: ["dev-scaleway-compose"]
    #pull_request:
    #  branches: ["main", "dev"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Login to Scaleway Container Registry
            uses: docker/login-action@v3
            with:
                username: nologin
                password: ${{ secrets.SCALEWAY_API_KEY }}
                registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
        -   name: Build the Docker image
            run: docker build -f ./ml-app/Dockerfile --build-context source-code=${{secrets.GIT_APP_URL}} -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app-test:latest
        -   name: Push the Docker Image
            run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app-test:latest
        
    deploy:
        # Deployment job
        runs-on: ubuntu-latest
        needs: build

        steps:
        #-   name: Setup SSH key
        #    uses: shimataro/ssh-key-action@v2
        #    with:   
        #        key: ${{ secrets.SSH_PRIVATE_KEY }}
        #        name: id_rsa # optional
        #        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        #-   name: Login to Scaleway Container Registry
        #    uses: docker/login-action@v3
        #    with:
        #        username: nologin
        #        password: ${{ secrets.SCALEWAY_API_KEY }}
        #        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
        -   name: Deploy to VM via SSH
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                #key_path: 
                #port: 22
                script: |
                    docker login ${{secrets.CONTAINER_REGISTRY_ENDPOINT}} -u nologin -p ${{ secrets.SCALEWAY_API_KEY }}
                    docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
                    docker stop ml-app-deploy || true
                    docker rm ml-app-deploy || true
                    docker run -d --name ml-app-deploy -p 8000:8000 ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/ml-app
